[server]
enableCORS = false
headless = true
port = 8501
maxUploadSize = 500

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1E1E1E"
font = "sans serif"
